import { bi } from "@/i18n/bi";

/** Header copy and fixed labels for each section page, as in the design. */
export const pages = {
  handbooks: {
    title: bi("Technical handbook library", "کتابخانه هندبوک‌های تخصصی"),
    lead: bi(
      "Planned titles and their chapter outlines, organised by dosage form and development stage. Open a title to see its chapters; each can also be commissioned as a company-specific edition.",
      "عنوان‌های برنامه‌ریزی‌شده و سرفصل فصل‌ها، به تفکیک شکل دارویی و مرحله توسعه. برای دیدن فصل‌ها روی عنوان بزنید؛ هر عنوان به‌صورت ویرایش اختصاصی برای یک شرکت نیز قابل سفارش است.",
    ),
  },
  suppliers: {
    title: bi(
      "Suppliers & manufacturers of pharmaceutical, supplement and cosmetic raw materials",
      "بانک تأمین‌کنندگان و تولیدکنندگان مواد اولیه دارویی، مکمل و آرایشی‌بهداشتی",
    ),
    lead: bi(
      "Domestic manufacturers and importers in Iran of pharmaceutical raw materials (APIs and excipients), vitamins and mineral salts, supplement ingredients and amino acids, and cosmetic raw materials. Search by Persian or English name, salt form or synonym.",
      "تولیدکنندگان داخلی و واردکنندگان مواد اولیه دارویی (مواد مؤثره و مواد جانبی)، ویتامین‌ها و املاح معدنی، مواد اولیه مکمل و آمینواسیدها، و مواد اولیه آرایشی‌بهداشتی در ایران. با نام فارسی یا انگلیسی، فرم نمکی یا مترادف جستجو کنید.",
    ),
    placeholder: bi(
      "e.g. Vitamin B1, thiamine hydrochloride, Zinc sulfate, polysorbate 80",
      "مثلاً: ویتامین B1، تیامین هیدروکلراید، Zinc sulfate، پلی‌سوربات ۸۰",
    ),
    clear: bi("Clear", "پاک کردن"),
    examples: bi("Examples:", "نمونه:"),
    exampleQueries: [
      "تیامین هیدروکلراید",
      "نیاسینامید",
      "زینک سولفات",
      "آویسل",
      "منیزیم استئارات",
      "پلی‌سوربات ۸۰",
      "هیالورونیک اسید",
      "Ascorbic acid",
      "متفورمین",
      "عصاره شیرین بیان",
    ],
    activity: bi("Type of activity", "نوع فعالیت"),
    types: {
      all: bi("All", "همه"),
      m: bi("Domestic manufacturer", "تولیدکننده داخلی"),
      t: bi("Importer and trader", "واردکننده و بازرگانی"),
    },
    category: bi("Category", "دسته"),
    categories: {
      all: bi("All", "همه"),
      api: bi("Active pharmaceutical ingredients (API)", "مواد مؤثره دارویی (API)"),
      vit: bi("Vitamins", "ویتامین‌ها"),
      min: bi("Minerals and mineral salts", "املاح معدنی و مینرال‌ها"),
      exc: bi("Excipients and solvents", "مواد جانبی (اکسیپیان) و حلال‌ها"),
      cos: bi("Cosmetic and personal-care raw materials", "مواد اولیه آرایشی‌بهداشتی"),
      sup: bi("Supplement ingredients and amino acids", "مواد اولیه مکمل و آمینواسیدها"),
      bio: bi("Biologics", "فرآورده‌های بیولوژیک"),
      std: bi("Laboratory reference standards", "استانداردهای مرجع آزمایشگاهی"),
    } as Record<string, ReturnType<typeof bi>>,
    sort: bi("Sort", "مرتب‌سازی"),
    sorts: {
      cred: bi("Credibility (most reliable first)", "اعتبار (معتبرترین بالا)"),
      rel: bi("Best match", "بیشترین تطابق"),
      site: bi("Plant / warehouse location (Tehran and Alborz first)", "محل کارخانه / انبار (تهران و البرز اول)"),
      type: bi("Domestic manufacturers first", "تولیدکننده داخلی اول"),
      name: bi("Company name", "نام شرکت"),
    },
    telOnly: bi("Only with a phone number", "فقط دارای تلفن"),
    countAll: bi("{n} companies in the directory — {p} materials listed", "{n} شرکت در پایگاه داده — {p} قلم ماده ثبت‌شده"),
    countQuery: bi("{n} companies for “{q}” — {t} with a phone number", "{n} شرکت برای «{q}» — {t} مورد با تلفن"),
    empty: bi(
      "No supplier is recorded for “{q}”. Try the English name or another salt form of the material, or remove the filters.",
      "برای «{q}» تأمین‌کننده‌ای در پایگاه داده ثبت نشده است. نام انگلیسی یا فرم نمکی دیگر ماده را امتحان کنید، یا فیلترها را بردارید.",
    ),
    needsCompleting: bi("Needs completing", "نیاز به تکمیل"),
    noPhone: bi("No phone", "بدون تلفن"),
    phone: bi("Phone", "تلفن"),
    address: bi("Address", "نشانی"),
    plant: bi("Plant / warehouse", "کارخانه / انبار"),
    location: bi("Location", "محل"),
    province: bi("province", "استان"),
    email: bi("Email", "ایمیل"),
    website: bi("Website", "وب‌سایت"),
    notRecorded: bi("Not recorded", "ثبت نشده"),
    copy: bi("Copy", "کپی"),
    copied: bi("Copied", "کپی شد"),
    otherProducts: bi("Other products of this company", "سایر محصولات این شرکت"),
    moreProducts: bi("More products", "بقیه محصولات"),
    searchSite: bi("Search “{q}” on this company's site ↗", "جستجوی «{q}» در سایت این شرکت ↗"),
    source: bi("Source", "منبع"),
    viaSearch: bi(" (product page title in web search)", " (عنوان صفحه محصول در جستجوی وب)"),
    orderTitle: bi("Display order", "ترتیب نمایش"),
    orderText: bi(
      "Results are listed by credibility: first syndicate-member manufacturers with a phone number, then companies whose contacts and catalogue come from their own website, then companies with only a website, and finally marketplaces, adverts and retailers. The order reflects how verifiable the information is, not an assessment of the company's quality.",
      "نتیجه‌ها به ترتیب اعتبار می‌آیند: اول تولیدکنندگان عضو سندیکا با تلفن، بعد شرکت‌هایی که تماس و کاتالوگشان از سایت خودشان برداشته شده، بعد شرکت‌های فقط دارای وب‌سایت، و در آخر بازارگاه‌ها، آگهی‌ها و خرده‌فروش‌ها. این ترتیب بر پایه قابل‌راستی‌آزمایی بودن اطلاعات است، نه ارزیابی کیفیت شرکت.",
    ),
    aboutTitle: bi("About this data", "درباره این داده‌ها"),
    about: [
      bi("Last updated: 17 Mehr 1405 (9 October 2026).", "آخرین به‌روزرسانی: ۱۷ مهر ۱۴۰۵"),
      bi(
        "Rows marked “no phone” were recorded from product-page titles in web search: the company has a sales page for that material on its site. Take the phone number from the company's own site; the “search on this company's site” link goes straight to that material.",
        "ردیف‌های «بدون تلفن» از روی عنوان صفحه محصول در جستجوی وب ثبت شده‌اند: یعنی آن شرکت در سایتش صفحه فروش آن ماده را دارد. تلفن را از سایت خود شرکت بردارید؛ لینک «جستجو در سایت این شرکت» مستقیم به همان ماده می‌رسد.",
      ),
      bi(
        "Each company's product list is what the company or the syndicate has declared and may be incomplete or out of date. Ask the company for the grade and licence before ordering.",
        "فهرست محصول هر شرکت همان چیزی است که خودش یا سندیکا اعلام کرده و ممکن است کامل یا به‌روز نباشد. پیش از سفارش، گرید و پروانه را از خود شرکت بپرسید.",
      ),
    ],
  },
  excipients: {
    title: bi("Pharmaceutical excipients database", "پایگاه داده مواد جانبی دارویی (اکسیپیان‌ها)"),
    lead: bi(
      "Excipients with functional category, dosage-form applicability and, where an established range exists, typical concentration. Search by English, Persian or trade name or by CAS Registry Number, or filter by function and dosage form.",
      "مواد جانبی دارویی با طبقه‌بندی عملکردی، کاربرد در اشکال دارویی و محدوده غلظت متداول (در صورت وجود محدوده مرجع). با نام انگلیسی، فارسی یا تجاری یا شماره CAS جستجو کنید، یا بر اساس عملکرد و شکل دارویی فیلتر کنید.",
    ),
    fn: bi("Functional category", "طبقه عملکردی"),
    form: bi("Dosage form", "شکل دارویی"),
    useLevel: bi("Typical concentration", "محدوده غلظت متداول"),
    allFunctions: bi("All functional categories", "همه طبقه‌های عملکردی"),
    allForms: bi("All dosage forms", "همه اشکال دارویی"),
    note: bi(
      "Concentration ranges are starting guidance and must be confirmed for each formulation against a compendial reference (e.g. Handbook of Pharmaceutical Excipients) and experimentally. q.s. (quantum satis) means the quantity required.",
      "محدوده‌های غلظت راهنمای شروع کار هستند و باید برای هر فرمولاسیون با مرجع معتبر (مانند Handbook of Pharmaceutical Excipients) و به‌صورت تجربی تأیید شوند. q.s. (quantum satis) یعنی به مقدار لازم.",
    ),
  },
  materials: {
    title: bi("API and raw material database", "پایگاه داده مواد مؤثره و مواد اولیه"),
    lead: bi(
      "Active pharmaceutical ingredients, vitamins and mineral salts with CAS Registry Number, molecular weight and a key solubility, stability or elemental-content note.",
      "مواد مؤثره دارویی، ویتامین‌ها و املاح معدنی با شماره CAS، وزن مولکولی و نکته کلیدی درباره حلالیت، پایداری یا درصد عنصر.",
    ),
    group: bi("Class", "رده"),
    allGroups: bi("All classes", "همه رده‌ها"),
    mw: bi("Molecular weight (g/mol)", "وزن مولکولی (g/mol)"),
    keyPoint: bi("Key property", "ویژگی کلیدی"),
  },
  tools: {
    title: bi("Pharmaceutical calculations", "محاسبات داروسازی"),
    lead: bi(
      "{n} calculators in three groups: formulation and manufacturing; solutions, physical pharmacy and stability; analysis and quality control. Results update as you type, and the governing equation and reference are shown under each one.",
      "{n} ماشین‌حساب در سه گروه: فرمولاسیون و تولید؛ محلول‌ها، داروسازی فیزیکی و پایداری؛ آنالیز و کنترل کیفیت. نتیجه هم‌زمان با ورود داده محاسبه می‌شود و معادله مبنا و مرجع زیر هر کدام آمده است.",
    ),
  },
  formulation: {
    title: bi("Starting formulation builder", "طراحی فرمول پایه"),
    lead: bi(
      "Select a dosage form to load a typical starting composition (% w/w). Adjust the percentages; the q.s. component and batch quantities are recalculated automatically.",
      "یک شکل دارویی انتخاب کنید تا ترکیب پایه متداول آن (درصد وزنی/وزنی) بارگذاری شود. درصدها را تغییر دهید؛ جزء q.s. و مقادیر بچ به‌طور خودکار محاسبه می‌شوند.",
    ),
    form: bi("Dosage form", "شکل دارویی"),
    batch: bi("Batch size (kg)", "اندازه بچ (کیلوگرم)"),
    fn: bi("Functional role", "نقش عملکردی"),
    material: bi("Example material", "ماده پیشنهادی"),
    kg: bi("kg per batch", "kg در بچ"),
    over: bi("The components add up to more than 100%.", "مجموع اجزا از 100% بیشتر است."),
    note: bi(
      "These compositions are starting points, not validated formulations. Drug–excipient compatibility, stability and performance must be established for each product.",
      "این ترکیب‌ها نقطه شروع هستند، نه فرمولاسیون اعتبارسنجی‌شده. سازگاری دارو و ماده جانبی، پایداری و عملکرد باید برای هر فرآورده اثبات شود.",
    ),
  },
  regulatory: {
    title: bi("Regulatory reference: CTD and ICH", "مرجع امور رگولاتوری: CTD و ICH"),
    lead: bi(
      "The Common Technical Document (ICH M4) module structure, the ICH guidelines most used in quality work, and the ICH Q1A(R2) stability storage conditions.",
      "ساختار ماژول‌های سند فنی مشترک (ICH M4)، پرکاربردترین راهنماهای ICH در حوزه کیفیت، و شرایط نگهداری مطالعات پایداری ICH Q1A(R2).",
    ),
    ctd: bi("Common Technical Document (CTD) structure", "ساختار سند فنی مشترک (CTD)"),
    ich: bi("ICH guidelines", "راهنماهای ICH"),
    code: bi("Code", "کد"),
    subject: bi("Subject", "موضوع"),
    stability: bi("Stability study conditions (ICH Q1A, general case)", "شرایط مطالعه پایداری (ICH Q1A، حالت کلی)"),
    study: bi("Study", "مطالعه"),
    storage: bi("Storage condition", "شرایط نگهداری"),
    minData: bi("Minimum data at submission", "حداقل داده هنگام ثبت"),
    stabilityRows: [
      { study: bi("Long-term", "بلندمدت"), condition: "25 °C ± 2 °C / 60% RH ± 5%  |  30 °C ± 2 °C / 65% RH ± 5%", data: bi("12 months", "12 ماه") },
      { study: bi("Intermediate", "میانی"), condition: "30 °C ± 2 °C / 65% RH ± 5%", data: bi("6 months", "6 ماه") },
      { study: bi("Accelerated", "تسریع‌شده"), condition: "40 °C ± 2 °C / 75% RH ± 5%", data: bi("6 months", "6 ماه") },
    ],
  },
  qa: {
    title: bi("Quality assurance and SOP library", "تضمین کیفیت و کتابخانه دستورالعمل‌ها"),
    lead: bi(
      "The pharmaceutical quality system (ICH Q10), quality risk management tools (ICH Q9(R1)), the key GMP references, and the master list of GMP procedures a manufacturing site requires, by department.",
      "سیستم کیفیت دارویی (ICH Q10)، ابزارهای مدیریت ریسک کیفیت \u2066(ICH Q9(R1))\u2069، مراجع کلیدی GMP و فهرست جامع دستورالعمل‌های GMP موردنیاز یک واحد تولید دارو به تفکیک واحد سازمانی.",
    ),
    library: bi("Standard operating procedure (SOP) library", "کتابخانه دستورالعمل‌های استاندارد (SOP)"),
    libraryLead: bi(
      "Each row gives the SOP title and its required scope.",
      "هر ردیف عنوان دستورالعمل و دامنه الزامی آن را نشان می‌دهد.",
    ),
    ready: bi(
      "The full text of all {n} SOPs is ready (in Persian): press “Full text” on a row.",
      "متن کامل هر {n} دستورالعمل آماده است: روی «متن کامل» در هر ردیف بزنید.",
    ),
    department: bi("Department", "واحد"),
    allDepartments: bi("All departments", "همه واحدها"),
    code: bi("Code", "کد"),
    sopTitle: bi("SOP title", "عنوان SOP"),
    covers: bi("Required scope", "دامنه الزامی"),
    fullText: bi("Full text", "متن کامل"),
    sops: bi("SOPs", "دستورالعمل"),
    codesNote: bi(
      "Codes are suggestions; each company can apply its own numbering system.",
      "کدها پیشنهادی‌اند و هر شرکت می‌تواند سیستم شماره‌گذاری خودش را به کار ببرد.",
    ),
    template: bi("Standard SOP template", "قالب استاندارد SOP"),
    templateHead: bi(
      "Header: title, code, revision number, effective date, next review date, prepared by, reviewed by and approved by (QA).",
      "سربرگ: عنوان، کد، شماره بازنگری، تاریخ اجرا، تاریخ بازنگری بعدی، تهیه‌کننده، بازبین و تأییدکننده (تضمین کیفیت).",
    ),
    templateItems: [
      bi("Purpose", "هدف"),
      bi("Scope", "دامنه کاربرد"),
      bi("Responsibilities", "مسئولیت‌ها"),
      bi("Definitions and abbreviations", "تعاریف و اختصارات"),
      bi("Materials and equipment", "مواد و تجهیزات"),
      bi("Procedure", "روش اجرا"),
      bi("Records and forms", "سوابق و فرم‌ها"),
      bi("References", "مراجع"),
      bi("Revision history", "تاریخچه بازنگری"),
    ],
    backToList: bi("SOP library", "کتابخانه دستورالعمل‌ها"),
    inPersian: bi("The full text of this SOP is written in Persian.", "متن کامل این دستورالعمل به فارسی است."),
    copy: bi("Copy text", "کپی متن"),
    copied: bi("Copied", "کپی شد"),
  },
};
